// Code generated by command: go run math_amd64.go -out ../math_amd64.s -pkg qm. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func Sqrt(x float32) float32
// Requires: SSE
TEXT ·Sqrt(SB), NOSPLIT|NOFRAME, $0-12
	MOVSS  x+0(FP), X0
	SQRTPS X0, X0
	MOVSS  X0, ret+8(FP)
	RET

// func InvSqrt(x float32) float32
// Requires: SSE
TEXT ·InvSqrt(SB), NOSPLIT|NOFRAME, $0-12
	MOVSS  x+0(FP), X0
	SQRTPS X0, X0
	RCPSS  X0, X0
	MOVSS  X0, ret+8(FP)
	RET
