// Code generated by command: go run vec2.amd64.go -out ../vec2.amd64.s -stubs ../vec2.amd64.go -pkg qm. DO NOT EDIT.

//go:build amd64

package qm

//go:nosplit
//go:noescape
func add_array_2_float32(l [2]float32, r [2]float32) [2]float32

//go:nosplit
func sub_array_2_float32(l [2]float32, r [2]float32) [2]float32

//go:nosplit
func mul_array_2_float32(l [2]float32, r [2]float32) [2]float32

//go:nosplit
func div_array_2_float32(l [2]float32, r [2]float32) [2]float32
