// Code generated by command: go run vec2.amd64.go -out ../vec2.amd64.s -stubs ../vec2.amd64.go -pkg qm. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func add_arrayof_2float32(l [2]float32, r [2]float32) [2]float32
// Requires: SSE
TEXT ·add_arrayof_2float32(SB), NOSPLIT|NOFRAME, $0-24
	MOVSS r_0+8(FP), X0
	ADDSS l+0(FP), X0
	MOVSS X0, ret_0+16(FP)
	MOVSS r_1+12(FP), X0
	ADDSS l+4(FP), X0
	MOVSS X0, ret_1+20(FP)
	RET

// func sub_arrayof_2float32(l [2]float32, r [2]float32) [2]float32
// Requires: SSE
TEXT ·sub_arrayof_2float32(SB), NOSPLIT|NOFRAME, $0-24
	MOVSS r_0+8(FP), X0
	SUBSS l+0(FP), X0
	MOVSS X0, ret_0+16(FP)
	MOVSS r_1+12(FP), X0
	SUBSS l+4(FP), X0
	MOVSS X0, ret_1+20(FP)
	RET

// func mul_arrayof_2float32(l [2]float32, r [2]float32) [2]float32
// Requires: SSE
TEXT ·mul_arrayof_2float32(SB), NOSPLIT|NOFRAME, $0-24
	MOVSS r_0+8(FP), X0
	MULSS l+0(FP), X0
	MOVSS X0, ret_0+16(FP)
	MOVSS r_1+12(FP), X0
	MULSS l+4(FP), X0
	MOVSS X0, ret_1+20(FP)
	RET

// func div_arrayof_2float32(l [2]float32, r [2]float32) [2]float32
// Requires: SSE
TEXT ·div_arrayof_2float32(SB), NOSPLIT|NOFRAME, $0-24
	MOVSS r_0+8(FP), X0
	DIVSS l+0(FP), X0
	MOVSS X0, ret_0+16(FP)
	MOVSS r_1+12(FP), X0
	DIVSS l+4(FP), X0
	MOVSS X0, ret_1+20(FP)
	RET
