// Code generated by command: go run vec2.amd64.go -out ../vec2.amd64.s -stubs ../vec2.amd64.go -pkg qm. DO NOT EDIT.

//go:build amd64

package qm

//go:nosplit
//go:noescape
func add_arrayof_2float32(l [2]float32, r [2]float32) [2]float32

//go:nosplit
//go:noescape
func sub_arrayof_2float32(l [2]float32, r [2]float32) [2]float32

//go:nosplit
//go:noescape
func mul_arrayof_2float32(l [2]float32, r [2]float32) [2]float32

//go:nosplit
//go:noescape
func div_arrayof_2float32(l [2]float32, r [2]float32) [2]float32
